---
name: "Release"
on:
  workflow_dispatch:
  pull_request_target:
    types: [closed]
    branches: [main]
jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/release.yaml@a0cf79bd8756e0a9c1555bf4975eae7ce7a8e8dc
    with:
      publish: true
      release-config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
