---
name: "Release"
on:
  workflow_dispatch:
  pull_request_target:
    types: [closed]
    branches: [main]
jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/release.yaml@6381f5d691a1ecf7d80126b0393a803224afd9ba
    with:
      publish: true
      release-config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
